services:
  zookeeper:
    image: zookeeper:3.8
    ports:
      - "2181:2181"

  pact-broker-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pact_broker
      POSTGRES_PASSWORD: pact_broker
      POSTGRES_DB: pact_broker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pact_broker"]
      interval: 5s
      timeout: 5s
      retries: 5

  pact-broker:
    image: pactfoundation/pact-broker:latest
    ports:
      - "9292:9292"
    depends_on:
      pact-broker-db:
        condition: service_healthy
    environment:
      PACT_BROKER_DATABASE_URL: postgres://pact_broker:pact_broker@pact-broker-db/pact_broker
      PACT_BROKER_LOG_LEVEL: INFO
