grpc.client.currency-rate.address=discovery:///currency-rate-provider
grpc.client.currency-rate.negotiation-type=plaintext
spring.cloud.zookeeper.connect-string=localhost:2181
spring.cloud.zookeeper.discovery.register=false
